from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            "rtsp_url",
            default_value="rtsp://172.20.10.2:554/live0",
            description="OS08A20 camera RTSP URL exported by sample_dtof_rtsp case7.",
        ),
        DeclareLaunchArgument(
            "dtof_port",
            default_value="2368",
            description="SS-LD-AS01 dToF UDP destination port.",
        ),
        DeclareLaunchArgument(
            "enable_dtof",
            default_value="false",
            description="Listen for dToF UDP and publish depth topics. Disabled for camera-only parking bring-up.",
        ),
        DeclareLaunchArgument(
            "record_dir",
            default_value="/home/ebaina/parking_sensor_records",
            description="Directory for raw packets, decoded frames, metadata, and previews.",
        ),
        DeclareLaunchArgument(
            "camera_scale",
            default_value="0.5",
            description="Scale decoded camera frames before publishing/recording.",
        ),
        DeclareLaunchArgument(
            "camera_rotate",
            default_value="none",
            description="Rotate camera frames before publishing: none, 180, 90cw, or 90ccw.",
        ),
        DeclareLaunchArgument(
            "camera_backend",
            default_value="ffmpeg_mjpeg",
            description="RTSP receiver backend: ffmpeg_mjpeg for lower latency, or opencv.",
        ),
        DeclareLaunchArgument(
            "camera_ffmpeg_low_delay",
            default_value="false",
            description="Use FFmpeg nobuffer/low_delay flags for camera RTSP decoding.",
        ),
        DeclareLaunchArgument(
            "publish_camera_raw",
            default_value="false",
            description="Publish /parking/camera/image_raw. Disable for lower bandwidth Foxglove viewing.",
        ),
        DeclareLaunchArgument(
            "camera_jpeg_quality",
            default_value="95",
            description="JPEG quality for camera compressed images when re-encoding is required.",
        ),
        DeclareLaunchArgument(
            "camera_publish_stride",
            default_value="1",
            description="Publish one camera frame every N decoded frames. Use >1 for low-latency Foxglove viewing.",
        ),
        DeclareLaunchArgument(
            "camera_record_stride",
            default_value="10",
            description="Record one camera JPEG every N decoded frames to reduce live-view CPU and disk load.",
        ),
        DeclareLaunchArgument(
            "publish_yolo_input",
            default_value="false",
            description="Publish a camera image stream optimized for YOLO inference/training.",
        ),
        DeclareLaunchArgument(
            "yolo_input_topic",
            default_value="/parking/camera/yolo_input_jpeg",
            description="CompressedImage topic containing the optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "yolo_input_publish_stride",
            default_value="1",
            description="Publish one YOLO input frame every N accepted camera frames.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_input_width",
            default_value="1280",
            description="Resize optimized YOLO camera input to this width; 0 keeps source width.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_roi_top_fraction",
            default_value="0.0",
            description="Top crop fraction for optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_roi_bottom_fraction",
            default_value="1.0",
            description="Bottom crop fraction for optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_clahe_clip_limit",
            default_value="2.0",
            description="CLAHE clip limit for optimized YOLO camera input; 0 disables CLAHE.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_sharpen_amount",
            default_value="0.35",
            description="Unsharp-mask amount for optimized YOLO camera input; 0 disables sharpening.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_gamma",
            default_value="1.0",
            description="Gamma correction for optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "yolo_camera_jpeg_quality",
            default_value="96",
            description="JPEG quality for optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "camera_drop_flat_frames",
            default_value="false",
            description="Drop flat gray camera frames before publishing/recording.",
        ),
        DeclareLaunchArgument(
            "camera_flat_luma_std_threshold",
            default_value="6.0",
            description="Luma standard deviation below this value is considered flat.",
        ),
        DeclareLaunchArgument(
            "camera_flat_color_delta_threshold",
            default_value="4.0",
            description="Color channel delta below this value is considered gray-like.",
        ),
        DeclareLaunchArgument(
            "camera_flat_reconnect_threshold",
            default_value="12",
            description="Reconnect the camera receiver after this many consecutive flat frames.",
        ),
        DeclareLaunchArgument(
            "visualize_window",
            default_value="false",
            description="Open an OpenCV preview window when a display is available.",
        ),
        DeclareLaunchArgument(
            "enable_recording",
            default_value="true",
            description="Write raw sensor data and metadata to record_dir.",
        ),
        DeclareLaunchArgument(
            "dtof_depth_record_stride",
            default_value="2",
            description="Record one parsed dToF depth npy every N packets; raw UDP packets are still recorded.",
        ),
        DeclareLaunchArgument(
            "sync_slop_ms",
            default_value="700.0",
            description="Maximum host timestamp gap for camera/dToF sync pairs.",
        ),
        DeclareLaunchArgument(
            "preview_stride",
            default_value="15",
            description="Generate one combined preview image every N dToF packets.",
        ),
        DeclareLaunchArgument(
            "dtof_visual_publish_stride",
            default_value="2",
            description="Publish one dToF JPEG visualization every N dToF packets.",
        ),
        DeclareLaunchArgument(
            "dtof_visual_jpeg_quality",
            default_value="80",
            description="JPEG quality for dToF pseudo-color and obstacle views.",
        ),
        DeclareLaunchArgument(
            "dtof_visual_width",
            default_value="480",
            description="Width of published dToF pseudo-color views.",
        ),
        DeclareLaunchArgument(
            "dtof_visual_height",
            default_value="360",
            description="Height of published dToF pseudo-color views.",
        ),
        DeclareLaunchArgument(
            "dtof_visual_max_mm",
            default_value="4000",
            description="Distance that maps to far color in dToF pseudo-color views.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_near_mm",
            default_value="500",
            description="Obstacle block near threshold in millimetres.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_warn_mm",
            default_value="1200",
            description="Obstacle block warning threshold in millimetres.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_noise_floor_mm",
            default_value="250",
            description="Ignore smaller dToF values for obstacle blocks to suppress near speckle noise.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_distance_percentile",
            default_value="25.0",
            description="Percentile used for supported near/warn obstacle distance estimates.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_min_support_pixels",
            default_value="16",
            description="Minimum close pixels required in a dToF zone before near/warn is reported.",
        ),
        DeclareLaunchArgument(
            "dtof_obstacle_min_support_ratio",
            default_value="0.20",
            description="Minimum close-pixel ratio in a dToF zone before near/warn is reported.",
        ),
        DeclareLaunchArgument(
            "publish_pointcloud",
            default_value="false",
            description="Publish /parking/dtof/points. Keep disabled for the default low-bandwidth Foxglove path.",
        ),
        DeclareLaunchArgument(
            "enable_vision_preprocess",
            default_value="true",
            description="Run pixel-only OpenCV preprocessing for uncalibrated parking-line candidates.",
        ),
        DeclareLaunchArgument(
            "enable_yolo_person",
            default_value="false",
            description="Run perception-only YOLO ONNX person detection on /parking/camera/image_jpeg.",
        ),
        DeclareLaunchArgument(
            "enable_parking_yolo",
            default_value="false",
            description="Run perception-only YOLO ONNX parking-slot detection on the optimized YOLO camera input.",
        ),
        DeclareLaunchArgument(
            "enable_parking_planner",
            default_value="true",
            description="Run the dry-run parking planner. It publishes diagnostics only and never sends actuator commands.",
        ),
        DeclareLaunchArgument(
            "enable_parking_controller_dry_run",
            default_value="true",
            description="Run the dry-run controller that publishes candidate STM32 V2 commands but never sends them.",
        ),
        DeclareLaunchArgument(
            "yolo_model_path",
            default_value="/home/ebaina/parking_models/yolov8n.onnx",
            description="Path to a YOLOv8/YOLO11-compatible ONNX model on the VM.",
        ),
        DeclareLaunchArgument(
            "yolo_process_stride",
            default_value="20",
            description="Run person detection on one camera JPEG frame every N received frames.",
        ),
        DeclareLaunchArgument(
            "yolo_confidence_threshold",
            default_value="0.50",
            description="Minimum person confidence for YOLO detections.",
        ),
        DeclareLaunchArgument(
            "yolo_nms_threshold",
            default_value="0.45",
            description="NMS IoU threshold for YOLO person detections.",
        ),
        DeclareLaunchArgument(
            "yolo_input_size",
            default_value="640",
            description="Square YOLO ONNX input size.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_model_path",
            default_value="/home/ebaina/parking_models/parking_slot.onnx",
            description="Path to the parking-slot YOLO ONNX model on the VM.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_class_names",
            default_value="Parking",
            description="Comma-separated class names in the parking YOLO model class-id order.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_empty_class_names",
            default_value="empty,empty_space,vacant,available,free",
            description="Parking YOLO class names treated as empty slots.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_occupied_class_names",
            default_value="occupied,ocupied,occupied_space,car,vehicle",
            description="Parking YOLO class names treated as occupied slots.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_slot_class_names",
            default_value="Parking,parking,parking_space,parking_slot,slot,space",
            description="Parking YOLO class names treated as slot geometry with unknown occupancy.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_include_unknown_as_slot",
            default_value="true",
            description="Treat unknown parking YOLO classes as slot candidates for early model testing.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_process_stride",
            default_value="3",
            description="Run parking YOLO on one optimized camera frame every N received frames.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_confidence_threshold",
            default_value="0.35",
            description="Minimum confidence for parking YOLO detections.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_nms_threshold",
            default_value="0.45",
            description="NMS IoU threshold for parking YOLO detections.",
        ),
        DeclareLaunchArgument(
            "parking_yolo_input_size",
            default_value="640",
            description="Square parking YOLO ONNX input size.",
        ),
        DeclareLaunchArgument(
            "parking_planner_fallback_to_pixel_candidates",
            default_value="true",
            description="Use pixel-only line candidates when fresh YOLO slot candidates are unavailable.",
        ),
        DeclareLaunchArgument(
            "parking_planner_stale_after_sec",
            default_value="1.5",
            description="Maximum age for YOLO or pixel candidate inputs accepted by the dry-run planner.",
        ),
        DeclareLaunchArgument(
            "parking_planner_max_steering_deg",
            default_value="25.0",
            description="Steering limit used only for dry-run control hints.",
        ),
        DeclareLaunchArgument(
            "parking_planner_nominal_reverse_speed_cm_s",
            default_value="3.0",
            description="Reverse speed shown only as a dry-run suggestion; commanded speed remains zero.",
        ),
        DeclareLaunchArgument(
            "parking_controller_required_stable_frames",
            default_value="5",
            description="Number of stable planner outputs before the dry-run controller marks a command candidate ready.",
        ),
        DeclareLaunchArgument(
            "parking_controller_max_target_center_shift_norm",
            default_value="0.08",
            description="Maximum normalized slot-center movement between frames considered stable.",
        ),
        DeclareLaunchArgument(
            "parking_controller_reverse_step_cm",
            default_value="5.0",
            description="Dry-run candidate reverse ARC step size in centimetres.",
        ),
        DeclareLaunchArgument(
            "parking_controller_approach_step_cm",
            default_value="3.0",
            description="Dry-run candidate straight reverse MOVE step size in centimetres.",
        ),
        DeclareLaunchArgument(
            "parking_controller_speed_gear",
            default_value="1",
            description="Dry-run candidate STM32 V2 speed gear.",
        ),
        DeclareLaunchArgument(
            "parking_controller_steering_sign",
            default_value="1.0",
            description="Dry-run mapping sign from planner steering hint to STM32 STE angle; calibrate before real motion.",
        ),
        DeclareLaunchArgument(
            "parking_controller_require_stm32_health",
            default_value="false",
            description="Require fresh /parking/stm32/health before marking dry-run command candidates ready.",
        ),
        DeclareLaunchArgument(
            "vision_process_stride",
            default_value="3",
            description="Process one camera JPEG frame every N received frames.",
        ),
        DeclareLaunchArgument(
            "vision_resize_width",
            default_value="960",
            description="Resize camera frames to this width before pixel-only preprocessing; 0 disables resizing.",
        ),
        DeclareLaunchArgument(
            "vision_roi_top_fraction",
            default_value="0.45",
            description="Top edge of the camera ROI as a fraction of image height.",
        ),
        DeclareLaunchArgument(
            "vehicle_length_cm",
            default_value="23.6",
            description="Vehicle total length in centimetres for parking-slot fit reporting.",
        ),
        DeclareLaunchArgument(
            "vehicle_width_cm",
            default_value="20.0",
            description="Vehicle total width in centimetres for parking-slot fit reporting.",
        ),
        DeclareLaunchArgument(
            "slot_side_clearance_cm",
            default_value="2.0",
            description="Required clearance on each side of the vehicle, in centimetres.",
        ),
        DeclareLaunchArgument(
            "slot_end_clearance_cm",
            default_value="3.0",
            description="Required clearance at front and rear of the vehicle, in centimetres.",
        ),
        DeclareLaunchArgument(
            "enable_stm32",
            default_value="false",
            description="Start the VM-side UDP receiver for board-forwarded STM32 serial data. Disabled by default for perception-only parking bring-up.",
        ),
        DeclareLaunchArgument(
            "stm32_udp_port",
            default_value="24680",
            description="UDP port for board-forwarded STM32 serial chunks.",
        ),
        DeclareLaunchArgument(
            "stm32_analysis_sample_bytes",
            default_value="8192",
            description="Rolling sample size for STM32 protocol-shape analysis.",
        ),
        Node(
            package="parking_bridge",
            executable="sensor_suite_node",
            name="parking_sensor_suite",
            output="screen",
            parameters=[{
                "rtsp_url": LaunchConfiguration("rtsp_url"),
                "dtof_port": LaunchConfiguration("dtof_port"),
                "enable_dtof": LaunchConfiguration("enable_dtof"),
                "record_dir": LaunchConfiguration("record_dir"),
                "camera_backend": LaunchConfiguration("camera_backend"),
                "camera_ffmpeg_low_delay": LaunchConfiguration("camera_ffmpeg_low_delay"),
                "camera_scale": LaunchConfiguration("camera_scale"),
                "camera_rotate": LaunchConfiguration("camera_rotate"),
                "publish_camera_raw": LaunchConfiguration("publish_camera_raw"),
                "camera_jpeg_quality": LaunchConfiguration("camera_jpeg_quality"),
                "camera_publish_stride": LaunchConfiguration("camera_publish_stride"),
                "camera_record_stride": LaunchConfiguration("camera_record_stride"),
                "publish_yolo_input": LaunchConfiguration("publish_yolo_input"),
                "yolo_input_topic": LaunchConfiguration("yolo_input_topic"),
                "yolo_input_publish_stride": LaunchConfiguration("yolo_input_publish_stride"),
                "yolo_input_width": LaunchConfiguration("yolo_camera_input_width"),
                "yolo_roi_top_fraction": LaunchConfiguration("yolo_camera_roi_top_fraction"),
                "yolo_roi_bottom_fraction": LaunchConfiguration("yolo_camera_roi_bottom_fraction"),
                "yolo_clahe_clip_limit": LaunchConfiguration("yolo_camera_clahe_clip_limit"),
                "yolo_sharpen_amount": LaunchConfiguration("yolo_camera_sharpen_amount"),
                "yolo_gamma": LaunchConfiguration("yolo_camera_gamma"),
                "yolo_jpeg_quality": LaunchConfiguration("yolo_camera_jpeg_quality"),
                "camera_drop_flat_frames": LaunchConfiguration("camera_drop_flat_frames"),
                "camera_flat_luma_std_threshold": LaunchConfiguration("camera_flat_luma_std_threshold"),
                "camera_flat_color_delta_threshold": LaunchConfiguration("camera_flat_color_delta_threshold"),
                "camera_flat_reconnect_threshold": LaunchConfiguration("camera_flat_reconnect_threshold"),
                "visualize_window": LaunchConfiguration("visualize_window"),
                "enable_recording": LaunchConfiguration("enable_recording"),
                "dtof_depth_record_stride": LaunchConfiguration("dtof_depth_record_stride"),
                "dtof_bind_ip": "0.0.0.0",
                "camera_frame_id": "os08a20_camera",
                "dtof_frame_id": "ss_ld_as01_dtof",
                "sync_slop_ms": LaunchConfiguration("sync_slop_ms"),
                "preview_stride": LaunchConfiguration("preview_stride"),
                "max_depth_mm": 10000,
                "publish_pointcloud": LaunchConfiguration("publish_pointcloud"),
                "dtof_visual_publish_stride": LaunchConfiguration("dtof_visual_publish_stride"),
                "dtof_visual_jpeg_quality": LaunchConfiguration("dtof_visual_jpeg_quality"),
                "dtof_visual_width": LaunchConfiguration("dtof_visual_width"),
                "dtof_visual_height": LaunchConfiguration("dtof_visual_height"),
                "dtof_visual_max_mm": LaunchConfiguration("dtof_visual_max_mm"),
                "dtof_obstacle_near_mm": LaunchConfiguration("dtof_obstacle_near_mm"),
                "dtof_obstacle_warn_mm": LaunchConfiguration("dtof_obstacle_warn_mm"),
                "dtof_obstacle_noise_floor_mm": LaunchConfiguration("dtof_obstacle_noise_floor_mm"),
                "dtof_obstacle_distance_percentile": LaunchConfiguration("dtof_obstacle_distance_percentile"),
                "dtof_obstacle_min_support_pixels": LaunchConfiguration("dtof_obstacle_min_support_pixels"),
                "dtof_obstacle_min_support_ratio": LaunchConfiguration("dtof_obstacle_min_support_ratio"),
            }],
        ),
        Node(
            package="parking_bridge",
            executable="vision_preprocess_node",
            name="parking_vision_preprocess",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_vision_preprocess")),
            parameters=[{
                "input_topic": "/parking/camera/image_jpeg",
                "debug_image_topic": "/parking/vision/line_debug",
                "candidates_topic": "/parking/parking_slot_candidates",
                "state_topic": "/parking/perception/state",
                "camera_frame_id": "os08a20_camera",
                "process_stride": LaunchConfiguration("vision_process_stride"),
                "resize_width": LaunchConfiguration("vision_resize_width"),
                "roi_top_fraction": LaunchConfiguration("vision_roi_top_fraction"),
                "vehicle_length_cm": LaunchConfiguration("vehicle_length_cm"),
                "vehicle_width_cm": LaunchConfiguration("vehicle_width_cm"),
                "slot_side_clearance_cm": LaunchConfiguration("slot_side_clearance_cm"),
                "slot_end_clearance_cm": LaunchConfiguration("slot_end_clearance_cm"),
                "jpeg_quality": 80,
            }],
        ),
        Node(
            package="parking_bridge",
            executable="yolo_person_node",
            name="parking_yolo_person",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_yolo_person")),
            parameters=[{
                "input_topic": LaunchConfiguration("yolo_input_topic"),
                "detections_topic": "/parking/yolo/person_detections",
                "view_topic": "/parking/yolo/person_view",
                "state_topic": "/parking/perception/state",
                "camera_frame_id": "os08a20_camera",
                "model_path": LaunchConfiguration("yolo_model_path"),
                "process_stride": LaunchConfiguration("yolo_process_stride"),
                "confidence_threshold": LaunchConfiguration("yolo_confidence_threshold"),
                "nms_threshold": LaunchConfiguration("yolo_nms_threshold"),
                "input_size": LaunchConfiguration("yolo_input_size"),
            }],
        ),
        Node(
            package="parking_bridge",
            executable="parking_yolo_node",
            name="parking_yolo",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_parking_yolo")),
            parameters=[{
                "input_topic": LaunchConfiguration("yolo_input_topic"),
                "detections_topic": "/parking/yolo/parking_detections",
                "view_topic": "/parking/yolo/parking_view",
                "state_topic": "/parking/perception/state",
                "camera_frame_id": "os08a20_camera",
                "model_path": LaunchConfiguration("parking_yolo_model_path"),
                "class_names": LaunchConfiguration("parking_yolo_class_names"),
                "empty_class_names": LaunchConfiguration("parking_yolo_empty_class_names"),
                "occupied_class_names": LaunchConfiguration("parking_yolo_occupied_class_names"),
                "slot_class_names": LaunchConfiguration("parking_yolo_slot_class_names"),
                "include_unknown_as_slot": LaunchConfiguration("parking_yolo_include_unknown_as_slot"),
                "process_stride": LaunchConfiguration("parking_yolo_process_stride"),
                "confidence_threshold": LaunchConfiguration("parking_yolo_confidence_threshold"),
                "nms_threshold": LaunchConfiguration("parking_yolo_nms_threshold"),
                "input_size": LaunchConfiguration("parking_yolo_input_size"),
            }],
        ),
        Node(
            package="parking_bridge",
            executable="parking_planner_node",
            name="parking_planner",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_parking_planner")),
            parameters=[{
                "yolo_detections_topic": "/parking/yolo/parking_detections",
                "pixel_candidates_topic": "/parking/parking_slot_candidates",
                "path_topic": "/parking/planner/path",
                "dry_run_cmd_topic": "/parking/controller/dry_run_cmd",
                "state_topic": "/parking/planner/state",
                "prefer_yolo": True,
                "fallback_to_pixel_candidates": LaunchConfiguration("parking_planner_fallback_to_pixel_candidates"),
                "stale_after_sec": LaunchConfiguration("parking_planner_stale_after_sec"),
                "vehicle_length_cm": LaunchConfiguration("vehicle_length_cm"),
                "vehicle_width_cm": LaunchConfiguration("vehicle_width_cm"),
                "slot_side_clearance_cm": LaunchConfiguration("slot_side_clearance_cm"),
                "slot_end_clearance_cm": LaunchConfiguration("slot_end_clearance_cm"),
                "max_steering_deg": LaunchConfiguration("parking_planner_max_steering_deg"),
                "nominal_reverse_speed_cm_s": LaunchConfiguration("parking_planner_nominal_reverse_speed_cm_s"),
            }],
        ),
        Node(
            package="parking_bridge",
            executable="parking_controller_dry_run_node",
            name="parking_controller_dry_run",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_parking_controller_dry_run")),
            parameters=[{
                "planner_path_topic": "/parking/planner/path",
                "stm32_health_topic": "/parking/stm32/health",
                "proposed_cmd_topic": "/parking/controller/proposed_cmd",
                "v2_candidate_topic": "/parking/controller/v2_candidate",
                "state_topic": "/parking/controller/state",
                "planner_stale_after_sec": LaunchConfiguration("parking_planner_stale_after_sec"),
                "require_stm32_health": LaunchConfiguration("parking_controller_require_stm32_health"),
                "required_stable_frames": LaunchConfiguration("parking_controller_required_stable_frames"),
                "max_target_center_shift_norm": LaunchConfiguration("parking_controller_max_target_center_shift_norm"),
                "reverse_step_cm": LaunchConfiguration("parking_controller_reverse_step_cm"),
                "approach_step_cm": LaunchConfiguration("parking_controller_approach_step_cm"),
                "speed_gear": LaunchConfiguration("parking_controller_speed_gear"),
                "steering_sign": LaunchConfiguration("parking_controller_steering_sign"),
                "servo_center_deg": 90.0,
                "servo_min_deg": 45.0,
                "servo_max_deg": 135.0,
                "max_abs_steering_hint_deg": LaunchConfiguration("parking_planner_max_steering_deg"),
            }],
        ),
        Node(
            package="parking_bridge",
            executable="stm32_udp_bridge",
            name="parking_stm32_udp_bridge",
            output="screen",
            condition=IfCondition(LaunchConfiguration("enable_stm32")),
            parameters=[{
                "bind_ip": "0.0.0.0",
                "udp_port": LaunchConfiguration("stm32_udp_port"),
                "record_dir": LaunchConfiguration("record_dir"),
                "enable_recording": LaunchConfiguration("enable_recording"),
                "status_period_sec": 1.0,
                "stale_after_sec": 2.0,
                "analysis_sample_bytes": LaunchConfiguration("stm32_analysis_sample_bytes"),
            }],
        ),
    ])
